chat_words_dict = {'afai': 'as far as i know',
 'af': 'away from keyboard',
 'asa': 'as soon as possible',
 'at': 'at the moment',
 'a': 'anytime, anywhere, anyplace',
 'ba': 'back at keyboard',
 'bb': 'be back soon',
 'bf': ' best friends forever',
 'b4': 'bye for now',
 'br': 'be right there',
 'bt': 'by the way',
 'b': 'before',
 'c': 'see you',
 'cul8': 'see you later',
 'cy': 'see you',
 'fa': 'frequently asked questions',
 'f': 'fingers crossed',
 'fwi': "for what it's worth",
 'fy': 'for your information',
 'ga': 'get a life',
 'g': 'genius',
 'gmt': 'great minds think alike',
 'gr': 'great!',
 'ic': 'i see',
 'isu': 'i seek you (also a chat program)',
 'il': ' i love you',
 'imh': 'in my honest/humble opinion',
 'im': 'in my opinion',
 'io': 'in other words',
 'ir': 'in real life',
 'kis': 'keep it simple, stupid',
 'ld': 'long distance relationship',
 'lma': 'laugh my a.. off',
 'lo': 'laughing out loud',
 'ltn': 'long time no see',
 'l8': 'later',
 'mt': 'my thoughts exactly',
 'm': 'mate',
 'nr': 'no reply necessary',
 'oi': 'oh i see',
 'pit': 'pain in the a..',
 'pr': 'parents are watching',
 'qpsa?\tque pasa?rof': 'rolling on the floor laughing',
 'roflo': 'rolling on the floor laughing out loud',
 'rotflma': 'rolling on the floor laughing my a.. off',
 'sk': 'skate',
 'stat': 'your sex and age',
 'as': 'age, sex, location',
 'th': 'thank you',
 'ttf': 'ta-ta for now!',
 'tty': 'talk to you later',
 'u': 'you',
 'u2': 'you too',
 'u4': 'yours for ever',
 'w': 'wait...',
 'wt': 'way to go!',
 'wu': 'where are you from?',
 'sic': '-d laugher',
 'tfw': ' that feeling when. tfw internet slang often goes in a caption to an image.',
 'mfw': ' my face when',
 'mrw': ' my reaction when',
 'ifyp': ' i feel your pain',
 'lol': ' laughing out loud',
 'tntl': ' trying not to laugh',
 'jk': ' just kidding',
 'idc': ' i don’t care',
 'ily': ' i love you',
 'imu': ' i miss you',
 'adih': ' another day in hell',
 'zzz': ' sleeping, bored, tired',
 'wywh': ' wish you were here',
 'time': ' tears in my eyes',
 'bae': ' before anyone else',
 'fimh': ' forever in my heart',
 'bsaaw': ' big smile and a wink',
 'bwl': ' bursting with laughter',
 'lmao': ' laughing my a** off',
 'csl': ' can’t stop laughing'}

